name: manta_dart
version: 0.1.0
description: Manta Protocol implementation for Dart
author: Alessandro Viganò
homepage: https://mantaprotocol.github.io/manta-python/html/index.html
documentation: https://mantaprotocol.github.io/manta-python/html/index.html
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mqtt_client: ^8.2.0
  decimal: ^0.3.2
  uuid: ^2.2.2
  json_annotation: '>=2.0.0'
  logging: ^1.0.1
  pointycastle: ^3.0.1
  asn1lib: ^0.6.4
  rsa_pkcs: ^1.1.1
  async: ^2.2.0

dev_dependencies:
  test: ^1.3.4
  build_runner: ^1.0.0
  json_serializable: '>=2.0.0'
  mockito: ^3.0.0
  pedantic: ^1.8.0
  grinder: ^0.9.0
  environment_config: ^2.2.5
  http: ^0.13.1
