name: manta_dart
version: 0.2.0
description: Manta Protocol implementation for Dart
author: Alessandro Viganò
homepage: https://mantaprotocol.github.io/manta-python/html/index.html
documentation: https://mantaprotocol.github.io/manta-python/html/index.html
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mqtt_client: ^9.6.5
  decimal: ^2.1.0
  uuid: ^3.0.6
  json_annotation: '>=2.0.0'
  logging: ^1.0.2
  pointycastle: ^3.5.2
  asn1lib: ^1.1.0
  rsa_pkcs: ^2.0.1
  async: ^2.8.2

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  json_serializable: '>=2.0.0'
  mockito: ^5.1.0
  pedantic: ^1.11.1
  grinder: ^0.9.0
  environment_config: ^3.0.0
  http: ^0.13.4
